language: node_js

node_js:
  - "12"

cache: npm

install:
  - npm ci
  - npm run build

script:
  - npm test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  keep-history: true
  local-dir: content/.vuepress/dist
  on:
    branch: master
